### ISSUE TITLE
mongo-edu download issue handout M101JS

### ISSUE THREAD

**Issue by ahmadmuiz** [przemyslawpluta/mongo-edu#66]
Hi,

I have an error when download handout course M101JS. Below the capture screen.
---------------------------------------------------------------------------------------------------------
$ mongo-edu -d "/e/github/mongo university/M101JS/Week 1" -h

 [ MONGO-EDU 0.2.50 ]

? MongoDB Uni User Name ahmalidi@gmail.com
? MongoDB Uni Password ********
> Searching [====================] 100%
? Select Courses: Current
? Hi Ahmad Muiz. Found 3 Courses. Select: M101JS: MongoDB for Node.js Developers

? Select From 1 Handouts. Download: All
i Downloading: week_1_introduction.11a3f97c8aad.zip
c:\Users\AHMAD MUIZ L\AppData\Roaming\npm\node_modules\mongo-edu\node_modules\fi
lesize\lib\filesize.js:44
                        throw new Error("Invalid arguments");
                        ^

Error: Invalid arguments
    at filesize (c:\Users\AHMAD MUIZ L\AppData\Roaming\npm\node_modules\mongo-ed
u\node_modules\filesize\lib\filesize.js:44:10)
    at Request.<anonymous> (c:\Users\AHMAD MUIZ L\AppData\Roaming\npm\node_modul
es\mongo-edu\lib\videos.js:83:69)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at reportState (c:\Users\AHMAD MUIZ L\AppData\Roaming\npm\node_modules\mongo
-edu\node_modules\request-progress\index.js:83:21)
    at call (c:\Users\AHMAD MUIZ L\AppData\Roaming\npm\node_modules\mongo-edu\no
de_modules\request-progress\node_modules\throttleit\index.js:28:16)
    at Object.throttled [as reportState] (c:\Users\AHMAD MUIZ L\AppData\Roaming\
npm\node_modules\mongo-edu\node_modules\request-progress\node_modules\throttleit
\index.js:20:26)
    at onData (c:\Users\AHMAD MUIZ L\AppData\Roaming\npm\node_modules\mongo-edu\
node_modules\request-progress\index.js:44:36)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)

**Comment by przemyslawpluta** [comment]
@ahmadmuiz fixed just upgrade to `mongo-edu 0.2.51`.

**Comment by ahmadmuiz** [comment]
Thanks!
