### ISSUE TITLE
npm install error mac os

### ISSUE THREAD

**Issue by rndmax** [przemyslawpluta/mongo-edu#71]
I have already installed on mac. I apologize for the hasty issue))

**Comment by rndmax** [comment]
I solved the problem with the installation but now getting this error:

`Error: Command failed: python /usr/local/lib/node_modules/mongo-edu/node_modules/youtube-dl/bin/youtube-dl --dump-json -f best https://youtu.be/04N3Z0k5RuA
  File "/usr/local/lib/node_modules/mongo-edu/node_modules/youtube-dl/bin/youtube-dl", line 2
SyntaxError: Non-ASCII character '\xcb' in file /usr/local/lib/node_modules/mongo-edu/node_modules/youtube-dl/bin/youtube-dl on line 3, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

    at ChildProcess.exithandler (child_process.js:203:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)`

please help me))
